### ISSUE TITLE
New entry doesn't show after sorting without refreshing

### ISSUE THREAD

**Issue by Lgreenbunny** [Milan9135/webs-of-site#2]
Inside the birthdate tracker page when adding the entry it shows immediately, but whenever you click any of the sorting row headers it disappears. It behaves normally after refreshing, though. (Shown by milan)

**Comment by Milan9135** [comment]
probably an issue with datatables

**Comment by Milan9135** [comment]
gonna try to change how the table is made in a fork

**Comment by Milan9135** [comment]
branch*

**Comment by Milan9135** [comment]
a
